### ISSUE TITLE
[Feature request] Separate tabs for Reading and Watching on home page

### ISSUE THREAD

**Issue by Jerico3241** [Emplexx/Aluminium#10]
Reading and watching on Startpage should be sperated because it's to much of a hassle if someone has many animes and mangas ongoing to scroll down.

**Comment by Emplexx** [comment]
Separated in what way, do you have an example in mind? They're already in separate sections

**Comment by Jerico3241** [comment]
I mean having a header in the start page like this in Crunchyroll.





Yahoo Mail: Suchen, organisieren, erobern 
 
  Am Di., März 26, 2024 at 14:31 schrieb ***@***.***>:   


Separated in what way, do you have an example in mind? They're already in separate sections

**Comment by Jerico3241** [comment]
![Screenshot_20240326_143342_com crunchyroll crunchyroid](https://github.com/Emplexx/Aluminium/assets/143882922/e3e3627f-c503-4377-8f42-87ed16d362ca)
![Screenshot_20240326_143354_moe emi aluminium](https://github.com/Emplexx/Aluminium/assets/143882922/97322548-7b63-414d-aefd-c03c2dcb891d)
Like Crunchyroll has one.

**Comment by Jerico3241** [comment]
If you ask me

**Comment by Jerico3241** [comment]
![Screenshot_20240326_144657_moe emi aluminium_edit_51219342352804](https://github.com/Emplexx/Aluminium/assets/143882922/15fa6657-aa7d-4682-8798-2385952eb0e5)
Or like you made it in the profiles tab

**Comment by Emplexx** [comment]
That's a good idea for huge watching lists for sure! I'm sorry to say though it'll probably be low priority for a while
Also this is a bit of an unprompted suggestion on my part, but you could try setting the anime/manga you haven't updated in a while as Paused to decrease the size of the list and hopefully make it easier to scroll through

**Comment by Emplexx** [comment]
Actually, how does the following sound? Instead of making them separate tabs the sections could expand/collapse. That way if you need to get to your manga, you could just tap the anime section to collapse it with no need to scroll.
This would also work way better with the current design of the home page that has shortcuts at the top (for Anime and Manga list) which may be customisable in the future

**Comment by Jerico3241** [comment]
Ok thank you for appreciating.

**Comment by Emplexx** [comment]
Collapsible sections added in 0.3.8
