### ISSUE TITLE
[Feature Request] Anime airing schedules

### ISSUE THREAD

**Issue by FujimiyaAmane-kun** [Emplexx/Aluminium#14]
I would like to request to add some new features on Aluminum App, That way, we can see the schedules of animes without a hassle, and   adding a dark mode to the new feature that i've requested, that would me more cool. ありがとう－ズ again...

**Comment by Emplexx** [comment]
To clarify, do you want airing schedules, something like this AniChart page? https://anichart.net/airing

**Comment by FujimiyaAmane-kun** [comment]
はい

**Comment by FujimiyaAmane-kun** [comment]
If it's okay to suggest, then i'll gonna be a supporting japanese bro, and if you want to add some translation in japanese, you can request for me if you'd like.

**Comment by FujimiyaAmane-kun** [comment]
I'll cooperate as much as i can.

**Comment by Emplexx** [comment]
Thank you, that's very kind of you! If I ever set up something to let others contribute translations, I'll let you know

**Comment by FujimiyaAmane-kun** [comment]
Ok, thanks again bro, when will this request appear on Aluminum App?

**Comment by Emplexx** [comment]
Aluminium is a hobby project and these things take time so I can't give any ETA

**Comment by FujimiyaAmane-kun** [comment]
はい、そうなんだ。
Anyway, i've message you on anilist.
Feel free to chat there or here, 'kay? ほんまにありがとう－ザ。

**Comment by Emplexx** [comment]
Added in 0.3.9
