### ISSUE TITLE
[Feature Request] See Details and Work Involving Author/Studio/Staff/Character

### ISSUE THREAD

**Issue by Fmoment1** [Emplexx/Aluminium#2]
Tapping on an author/studio/staff/character would show their details/bio and all the anime/manga produced by that author/studio/staff or having that specific character.

For example:

- Tapping on the studio MADHOUSE would show a list of all the anime produced by that studio.
- Tapping on Akira Toriyama would show his details/bio and a list of all anime/manga he's worked on.
- Tapping on Joe Hisaishi would show his details/bio and a list of all anime he's worked on (in this case, done the soundtrack for).
- Tapping on Luffy D. Monkey would show his details/bio and a list of all anime/manga he's a part of.

**Comment by Emplexx** [comment]
Studios are added in 0.2.3, the rest will hopefully come soon

**Comment by Emplexx** [comment]
Characters & staff are now live in 0.3
