### ISSUE TITLE
missing origin for non-japanease items

### ISSUE THREAD

**Issue by l2eused** [Emplexx/Aluminium#29]
for example: [Xian Wang De Richang Shenghuo](https://anilist.co/anime/114121/Xian-Wang-De-Richang-Shenghuo/)

This item in anilist.co, format is showing as **ONA (Chinese)** but in app, it doesn't.

not sure if this effect to manga or not (I didn't use it) so please check that also.

Thanks

**Comment by l2eused** [comment]
ahh, I just noticed that **Status** isn't show in details page also.

edited: I think this is necessary especially on item that **hiatus**...

**Comment by Emplexx** [comment]
Sorry, I forgot to add the origin, I will add a row to the details section later

As for the status, it is shown right under the title of anime/manga, only when relevant. For example, if something is not yet released, cancelled, or on hiatus, you will see it there. If a manga is publishing it will say "releasing",  though if an anime is airing you can tell by the next episode countdown so it's not needed.

**Comment by Emplexx** [comment]
Added in 0.3.17
