### ISSUE TITLE
[Bug] Sanitize complex Unicode (Emoji) characters before posting/replying

### ISSUE THREAD

**Issue by nattadasu** [Emplexx/Aluminium#3]
The bug will happened when you want to create a post or replying to a post with complex Unicode characters (Emoji is the biggest use case)

Why? AniList seems to use MySQL as their database backend and their system does not support emoji space. Read [Emoji Support / How do I use emojis?](https://anilist.co/forum/thread/4273) and [GoBusto's post](https://anilist.co/activity/17580647) and [related post](https://anilist.co/activity/24221916).

The only workaround is converting those emoji to HTML character entity.

### Reproduce Steps

1. Create a new post, send a post reply, or reply to a forum
2. Embed an emoji to the post
3. Observe

### Expected Behavior

Post will retain its characters

### Observed Behavior

Some characters will be replaced to `?` or sometime missing. 

### Screenshots

![Screenshot_2024-01-01-14-51-40-252_moe.emi.aluminium.jpg](https://github.com/Emplexx/Aluminium/assets/49780229/fdc1386b-cb1f-4f77-bff1-8f1733796d37)

![Screenshot_2024-01-01-14-51-49-363_moe.emi.aluminium.jpg](https://github.com/Emplexx/Aluminium/assets/49780229/67751796-f28b-4803-a770-2724735eb044)

**Comment by Emplexx** [comment]
Thanks for the request! I now fixed this, you'll see it in the next update
