### ISSUE TITLE
Decimal note doesn't work

### ISSUE THREAD

**Issue by Tobi-san03** [Emplexx/Aluminium#30]
Hello. I use the decimal note in anilist, and your application has this option, but it doesn't allow me to enter a decimal note, only integer.

Decimal note (example: 7.5)
Whole grade (example: 7)

**Comment by Emplexx** [comment]
Please provide a video of this issue. As far as I am aware this is supported already

**Comment by Tobi-san03** [comment]
https://github.com/user-attachments/assets/f799fd09-0601-4363-9ee4-0a1bf1e22340

**Comment by Emplexx** [comment]
Wow, I'm sorry about that. It doesn't happen to me and I can't think off the top of my head what could be causing it. 

I don't know if I will be able to fix this soon.. Could you try going to the app settings > general > Slider step size, and setting it to 1/20th or Unlocked, and then trying to input your score using the slider instead of typing it in, as a workaround?

Also it would be great if you could tell me what language your device is set to.

**Comment by Tobi-san03** [comment]
As you can see the 1/20 didn't work, but the 
"None (unlocked)" even caught on, but I don't have much control. The language on my cell phone is Brazilian Portuguese.

**Comment by Tobi-san03** [comment]
Recorder_07082024_100143.mp4 -->

**Comment by Tobi-san03** [comment]
> 
> 
> As you can see the 1/20 didn't work, but the 
> "None (unlocked)" even caught on, but I don't have much control. The language on my cell phone is Brazilian Portuguese.

I thought I sent you the video of that last comment, and I ended up deleting the video and now I went to see it and the video had an error

**Comment by Emplexx** [comment]
You can try uploading it again

**Comment by Tobi-san03** [comment]
Reinstalar não ajudou, continua bugado.

Em qua., 7 de ago. de 2024 12:46, emi ***@***.***> escreveu:

**Comment by Tobi-san03** [comment]
Reinstalling didn't help, it's still buggy. Sorry for deleting it, it was written in Portuguese.

**Comment by Tobi-san03** [comment]
Reinstalling didn't help, it's still buggy. Sorry for deleting it, it was written in Portuguese.

**Comment by Emplexx** [comment]
I meant you can try uploading the video again so I can take a look

**Comment by Tobi-san03** [comment]
Tá, vou tentar

Em qua., 7 de ago. de 2024 12:46, emi ***@***.***> escreveu:

**Comment by Tobi-san03** [comment]
> I meant you can try uploading the video again so I can take a look

Let me do it, but I had to change the language on my cell phone from Portuguese to English

**Comment by Tobi-san03** [comment]
> > I meant you can try uploading the video again so I can take a look
> 
> Let me do it, but I had to change the language on my cell phone from Portuguese to English

The bad thing is that every time I rate an anime, I'll have to change the language on my phone.

**Comment by Tobi-san03** [comment]
Now that we understand what was happening, is there a way to solve it?

**Comment by Emplexx** [comment]
Can confirm, I managed to reproduce the issue by setting my phone language to Portuguese Brazil. I will try to debug and fix this in the future

**Comment by Tobi-san03** [comment]
Will you post the graphics and stats?

**Comment by Emplexx** [comment]
What

**Comment by Tobi-san03** [comment]
The graphs and statistics available in anilist

**Comment by Emplexx** [comment]
Is this related to the decimal score field not working?

**Comment by Tobi-san03** [comment]
No, I'm asking if it will be available in the app in the future?

**Comment by Emplexx** [comment]
Please open a different issue if you have a feature request

**Comment by Emplexx** [comment]
Fixed in 0.3.17
