### ISSUE TITLE
[Feature Request] Filter list posts by media type

### ISSUE THREAD

**Issue by Murilogs1910** [Emplexx/Aluminium#4]
## Request
Divide the "Lists" filter on the "Posts" tab was divided into "Manga" and "Anime".

## Why
Being mostly a manga reader, I generally don't care about anime activities. Being able to hide those would be great.

**Comment by Emplexx** [comment]
Thanks for the feature request! Do you want this only on the main Posts tab, or the one on user profiles as well?

**Comment by Emplexx** [comment]
You'll see it in the next update!
