### ISSUE TITLE
Copy description of anime/manga

### ISSUE THREAD

**Issue by Fmoment1** [Emplexx/Aluminium#46]
Currently, there's no way to copy the description of an anime/manga from the app without taking a screenshot and using OCR features (Google Lens), etc. This could be done in one of two ways:

1. Tap-and-hold on the description to copy the entire description (like what happens for titles).

2. Tap-and-hold on the description to enable text selection and select which part of the description we'd like to copy.

Either one is fine! The 2nd option is actually already present for copying descriptions from Staff or Characters, so I guess you could go with that for consistency.

**Comment by Emplexx** [comment]
Added in 0.3.17
