### ISSUE TITLE
Your following feed is empty

### ISSUE THREAD

**Issue by LightningRocks** [Emplexx/Aluminium#47]
What the title says. I have over 260 people that I am following and I cannot see the status of any of them in the feed within the app. The global feed does work as normal. I love the work being put into this app since AniList does not have one themselves. Keep up the great work :)
![Screenshot_20241119_002616_Aluminium](https://github.com/user-attachments/assets/8cc8c5a8-828e-4c79-94d3-7db827fe71f0)

**Comment by Emplexx** [comment]
Does this always happen? Or does it sometimes work, sometimes not?

**Comment by LightningRocks** [comment]
It always happens to me. I have yet to see it work since I noticed the bug

**Comment by Emplexx** [comment]
Hm.. In that case, does this happen to you in other AniList clients, like AniHyou, AL-chan, etc?
This has been reported on the forum thread on AniList before, and I've been monitoring it ever since. It happens to me sometimes but when it does, the same is happening in other clients,  I'm pretty sure this is (unfortunately) an issue with the API

**Comment by LightningRocks** [comment]
I'm not completely sure but I don't think a lot of other clients don't even offer checking your feed either globally or friends wise from what I know. I've downloaded and tried most of the Android options from the list at some point and used AniLib until they added ads with an update. I am at least sure that AniLib did not have a feed. 

I do know about the API issues so it could be related to that I suppose. Hope that Nick and Nazo figure it out soon. Cause they've tried to fix it several times now and have had to roll back updates or restrict the API cause of stuff

**Comment by LightningRocks** [comment]
Okay after testing a different app AniTrend. They had status posts work in it but not progress updates. So it seems to be a mixed bag possibly

**Comment by Emplexx** [comment]
Does the following feed not work for you at all regardless of the filters applied, e.g. can you view just the status posts (like you can in AniTrend)?

**Comment by LightningRocks** [comment]
![Screenshot_20241120_191655_Aluminium](https://github.com/user-attachments/assets/bcb47492-1905-4894-8526-0b9bcf49d50e)

Still does not work with filters on or off if I specifically want to check for my following on Aluminium. Everything works with global. On AniTrend it was that following status posts worked but not list updates

**Comment by Emplexx** [comment]
Is there any chance you would be willing to debug this further and could contact me on discord or via email? I could try changing the query a bit, send you a debug build, and we could see if that fixes the issue

**Comment by LightningRocks** [comment]
I'm okay with that. I will contact you on Discord

**Comment by Emplexx** [comment]
Should be fixed in 0.3.17
