### ISSUE TITLE
App crashing on trying to load any page except the starting feed

### ISSUE THREAD

**Issue by ako256** [Emplexx/Aluminium#49]
Device: Nothing Phone 2
OS Version: Android 15 (NothingOS 3.0)

Issue: The app keeps crashing whenever I try to go to any other app section. This has started occuring ever since I've updated my phone to Android 15 (it's a beta version for my phone) I've attached a video of the issue below. Btw thanks for this app!

https://github.com/user-attachments/assets/fa9485ca-a137-4def-9aae-609329e72b30

**Comment by Emplexx** [comment]
Thanks for reporting this, I'll look into it

**Comment by Emplexx** [comment]
Could you please try this build and tell me if you run into the same issue? https://we.tl/t-RFCoS4GM2O

**Comment by ako256** [comment]
Yeah I'm running into the same issue in this build

**Comment by Emplexx** [comment]
Have you changed your system font in some way? I can see the status bar clock using Inter.

**Comment by ako256** [comment]
Oh yeah I'm using inter as my system font, it was a new 'feature' in my phone's update. I switched the font back to roboto and now the app is working perfectly

**Comment by Emplexx** [comment]
Unfortunately that seems to be the only workaround for now. I can see in the Play Console that this crash is native, and it has something to do with fonts. I also found other people online (that have a Nothing Phone and updated to the 15 beta) experiencing the same problem in other apps. Either way I don't really know what to do about it so I can only hope they'll fix this issue in the stable 15 update.

**Comment by ako256** [comment]
I see, I'll try sending a crash report to them as well. Thanks!

**Comment by Emplexx** [comment]
Could you also please try this build, with that Inter system font option enabled? https://we.tl/t-eF9uWuo5wa
I disabled the custom font of the app in this one, so I want to know if it also crashes

**Comment by ako256** [comment]
This one is working perfectly with inter font as system font! Everything seems to be loading just fine.

Is it ok to use this version of the app for the time being?

**Comment by Emplexx** [comment]
That's great to hear, maybe I'll try to add a workaround to the app so that it doesn't load custom fonts if it detects an Android 15 Nothing device, if that's even possible... Would you be down to test this in the future?

Also, yes, this version of the app should work fine

**Comment by ako256** [comment]
Yeah I'd be happy to test that!

**Comment by Emplexx** [comment]
Hello, here's another build: https://we.tl/t-szALkXzSDO
Unlike the last one where I just disabled custom fonts, this one should hopefully detect that you're using a Nothing device and apply a style overlay. I would like to know if it works! Thank you

**Comment by ako256** [comment]
This one is also working perfectly with both inter and roboto as my system font!

Additionally, I think it would be better if instead of looking for nothing devices exclusively, the app disabled custom font automatically if it crashes because of it. I'm not a developer though so idk if this would work in practice.

**Comment by Emplexx** [comment]
I'm happy to hear that! 

Also I totally agree, but I don't really know how I would detect the crash in order to do that, especially considering that it's native... (And I can check for the manufacturer/brand of the phone because these are constants from build properties). Another option would be to have a way for users to manually disable app fonts to prevent the crash, but that means the app still would crash beforehand and ultimately result in a subpar user experience. 

Anyways I'll try to release this change in an update soon. Thank you so much for the help with testing!

**Comment by Emplexx** [comment]
Fixed in v0.3.18 that just went live

**Comment by ako256** [comment]
Fair enough, I don't know much about android dev anyways so i was shooting in the dark lol. I'm glad I could help. Thank you for the app!
