### ISSUE TITLE
[Feature Request] Show external & streaming links on media pages

### ISSUE THREAD

**Issue by Jerico3241** [Emplexx/Aluminium#5]
It would be really nice to have links in the animes that redirects you to where someone can watch it.

**Comment by Emplexx** [comment]
Just to make sure, do you mean these? 
![image](https://github.com/Emplexx/Aluminium/assets/64900852/2b972b54-df8d-482f-8600-6b3b2cee7d49)
![image](https://github.com/Emplexx/Aluminium/assets/64900852/2acea812-c061-4780-a6bb-5d8f25ffe19a)

**Comment by Jerico3241** [comment]
Yes
