### ISSUE TITLE
Missing Capitalization of First Letters

### ISSUE THREAD

**Issue by Fmoment1** [Emplexx/Aluminium#9]
When you begin replying to a status or comment on a forum post or write a note, the first letter isn't auto capitalized, nor is the letter after a period/full stop. This is just a minor nitpick so idk what else to say, take your time and thank you for such a good looking app lol.

**Comment by Emplexx** [comment]
I see, I never realised this was missing since I have auto-capitalisation disabled in my keyboard settings. I found the fix so it'll be there in the next update 😊

**Comment by Emplexx** [comment]
Fixed in 0.3.8
